apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ebs_app_new_java"

  links:
    - url: https://github.com/RohanAwasthi/aws-elasticbeanstalk-20231027085848
      title: "ebs_app_new_java"
      icon: code

  labels:
    system: web-apps
    trackid: "aws-elasticbeanstalk-20231027085848"
    environmentname: myenv-java

  tags:
    - java
    - aws
    - "applicationtype-webapplication"

  annotations:
    # add elastic beanstalk annotation
    jenkins.io/github-folder: 'custom-actions/tf-ebs_app_new_java'
    github.com/project-slug: RohanAwasthi/aws-elasticbeanstalk-20231027085848
    backstage.io/techdocs-ref: dir:.
    backstage.io/linguist: https://github.com/ItRachii/spring-boot-ebs
    sonarqube.org/project-key: 'demo-app/aws-elb-java'

spec:
  type: service
  lifecycle: experimental
  system: elasticbeanstalk
  owner: "group:default/ey"
